### PR TITLE
feat: logout functionality integration

### PR DESCRIPTION
**Pull request by garrettmroberts**
Updated UI on navbar for logout button.  Hitting logout endpoint now.  Redirect on success and toast on fail.

### CODE REVIEW

**Comment by topboyasante** [comment]
hi @garrettmroberts . thanks for the PR!
I do have some changes i'd like us to do.
Users can logout with supabase (if they signed in with OAuth) or the api route (if they signed in with email & password).
We need to check if there's a supabase user logged in, and then log him out with supabase. if not, we log him out with the API route.

**Comment by garrettmroberts** [comment]
@topboyasante This should be ready to go now. Only thing I was unsure of was where we were gathering email/pw data on the current user so I left that empty for the time being on the logout method.  If there is already an implemented method for fetching that data, let me know and I can adjust accordingly.

**Comment by topboyasante** [comment]
@garrettmroberts we're yet to do that. but thanks!

**Comment by topboyasante** [comment]
LGTM

**Pull request merged**
